/**
 * @fileoverview gRPC-Web generated client stub for teste
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v4.23.0-rc3
// source: movie.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.teste = require('./movie_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.teste.MovieServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.teste.MovieServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.teste.Command,
 *   !proto.teste.Response>}
 */
const methodDescriptor_MovieService_CreateMovie = new grpc.web.MethodDescriptor(
  '/teste.MovieService/CreateMovie',
  grpc.web.MethodType.UNARY,
  proto.teste.Command,
  proto.teste.Response,
  /**
   * @param {!proto.teste.Command} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.teste.Response.deserializeBinary
);


/**
 * @param {!proto.teste.Command} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.teste.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.teste.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.teste.MovieServiceClient.prototype.createMovie =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/teste.MovieService/CreateMovie',
      request,
      metadata || {},
      methodDescriptor_MovieService_CreateMovie,
      callback);
};


/**
 * @param {!proto.teste.Command} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.teste.Response>}
 *     Promise that resolves to the response
 */
proto.teste.MovieServicePromiseClient.prototype.createMovie =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/teste.MovieService/CreateMovie',
      request,
      metadata || {},
      methodDescriptor_MovieService_CreateMovie);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.teste.Command,
 *   !proto.teste.Movie>}
 */
const methodDescriptor_MovieService_ListMoviesByCast = new grpc.web.MethodDescriptor(
  '/teste.MovieService/ListMoviesByCast',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.teste.Command,
  proto.teste.Movie,
  /**
   * @param {!proto.teste.Command} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.teste.Movie.deserializeBinary
);


/**
 * @param {!proto.teste.Command} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.teste.Movie>}
 *     The XHR Node Readable Stream
 */
proto.teste.MovieServiceClient.prototype.listMoviesByCast =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/teste.MovieService/ListMoviesByCast',
      request,
      metadata || {},
      methodDescriptor_MovieService_ListMoviesByCast);
};


/**
 * @param {!proto.teste.Command} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.teste.Movie>}
 *     The XHR Node Readable Stream
 */
proto.teste.MovieServicePromiseClient.prototype.listMoviesByCast =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/teste.MovieService/ListMoviesByCast',
      request,
      metadata || {},
      methodDescriptor_MovieService_ListMoviesByCast);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.teste.Command,
 *   !proto.teste.Movie>}
 */
const methodDescriptor_MovieService_ListMoviesByGenres = new grpc.web.MethodDescriptor(
  '/teste.MovieService/ListMoviesByGenres',
  grpc.web.MethodType.SERVER_STREAMING,
  proto.teste.Command,
  proto.teste.Movie,
  /**
   * @param {!proto.teste.Command} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.teste.Movie.deserializeBinary
);


/**
 * @param {!proto.teste.Command} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.teste.Movie>}
 *     The XHR Node Readable Stream
 */
proto.teste.MovieServiceClient.prototype.listMoviesByGenres =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/teste.MovieService/ListMoviesByGenres',
      request,
      metadata || {},
      methodDescriptor_MovieService_ListMoviesByGenres);
};


/**
 * @param {!proto.teste.Command} request The request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!grpc.web.ClientReadableStream<!proto.teste.Movie>}
 *     The XHR Node Readable Stream
 */
proto.teste.MovieServicePromiseClient.prototype.listMoviesByGenres =
    function(request, metadata) {
  return this.client_.serverStreaming(this.hostname_ +
      '/teste.MovieService/ListMoviesByGenres',
      request,
      metadata || {},
      methodDescriptor_MovieService_ListMoviesByGenres);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.teste.Command,
 *   !proto.teste.Response>}
 */
const methodDescriptor_MovieService_UpdateMovie = new grpc.web.MethodDescriptor(
  '/teste.MovieService/UpdateMovie',
  grpc.web.MethodType.UNARY,
  proto.teste.Command,
  proto.teste.Response,
  /**
   * @param {!proto.teste.Command} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.teste.Response.deserializeBinary
);


/**
 * @param {!proto.teste.Command} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.teste.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.teste.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.teste.MovieServiceClient.prototype.updateMovie =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/teste.MovieService/UpdateMovie',
      request,
      metadata || {},
      methodDescriptor_MovieService_UpdateMovie,
      callback);
};


/**
 * @param {!proto.teste.Command} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.teste.Response>}
 *     Promise that resolves to the response
 */
proto.teste.MovieServicePromiseClient.prototype.updateMovie =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/teste.MovieService/UpdateMovie',
      request,
      metadata || {},
      methodDescriptor_MovieService_UpdateMovie);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.teste.Command,
 *   !proto.teste.Response>}
 */
const methodDescriptor_MovieService_DeleteMovie = new grpc.web.MethodDescriptor(
  '/teste.MovieService/DeleteMovie',
  grpc.web.MethodType.UNARY,
  proto.teste.Command,
  proto.teste.Response,
  /**
   * @param {!proto.teste.Command} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.teste.Response.deserializeBinary
);


/**
 * @param {!proto.teste.Command} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.teste.Response)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.teste.Response>|undefined}
 *     The XHR Node Readable Stream
 */
proto.teste.MovieServiceClient.prototype.deleteMovie =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/teste.MovieService/DeleteMovie',
      request,
      metadata || {},
      methodDescriptor_MovieService_DeleteMovie,
      callback);
};


/**
 * @param {!proto.teste.Command} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.teste.Response>}
 *     Promise that resolves to the response
 */
proto.teste.MovieServicePromiseClient.prototype.deleteMovie =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/teste.MovieService/DeleteMovie',
      request,
      metadata || {},
      methodDescriptor_MovieService_DeleteMovie);
};


module.exports = proto.teste;

