# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import movie_pb2 as movie__pb2


class MovieServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMovie = channel.unary_unary(
                '/teste.MovieService/CreateMovie',
                request_serializer=movie__pb2.Movie.SerializeToString,
                response_deserializer=movie__pb2.Response.FromString,
                )
        self.ListMoviesByCast = channel.unary_stream(
                '/teste.MovieService/ListMoviesByCast',
                request_serializer=movie__pb2.Command.SerializeToString,
                response_deserializer=movie__pb2.Movie.FromString,
                )
        self.ListMoviesByGenres = channel.unary_stream(
                '/teste.MovieService/ListMoviesByGenres',
                request_serializer=movie__pb2.Command.SerializeToString,
                response_deserializer=movie__pb2.Movie.FromString,
                )
        self.UpdateMovie = channel.unary_unary(
                '/teste.MovieService/UpdateMovie',
                request_serializer=movie__pb2.Movie.SerializeToString,
                response_deserializer=movie__pb2.Response.FromString,
                )
        self.DeleteMovie = channel.unary_unary(
                '/teste.MovieService/DeleteMovie',
                request_serializer=movie__pb2.Command.SerializeToString,
                response_deserializer=movie__pb2.Response.FromString,
                )


class MovieServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMoviesByCast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMoviesByGenres(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMovie,
                    request_deserializer=movie__pb2.Movie.FromString,
                    response_serializer=movie__pb2.Response.SerializeToString,
            ),
            'ListMoviesByCast': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMoviesByCast,
                    request_deserializer=movie__pb2.Command.FromString,
                    response_serializer=movie__pb2.Movie.SerializeToString,
            ),
            'ListMoviesByGenres': grpc.unary_stream_rpc_method_handler(
                    servicer.ListMoviesByGenres,
                    request_deserializer=movie__pb2.Command.FromString,
                    response_serializer=movie__pb2.Movie.SerializeToString,
            ),
            'UpdateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMovie,
                    request_deserializer=movie__pb2.Movie.FromString,
                    response_serializer=movie__pb2.Response.SerializeToString,
            ),
            'DeleteMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMovie,
                    request_deserializer=movie__pb2.Command.FromString,
                    response_serializer=movie__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'teste.MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MovieService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teste.MovieService/CreateMovie',
            movie__pb2.Movie.SerializeToString,
            movie__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListMoviesByCast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/teste.MovieService/ListMoviesByCast',
            movie__pb2.Command.SerializeToString,
            movie__pb2.Movie.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListMoviesByGenres(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/teste.MovieService/ListMoviesByGenres',
            movie__pb2.Command.SerializeToString,
            movie__pb2.Movie.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teste.MovieService/UpdateMovie',
            movie__pb2.Movie.SerializeToString,
            movie__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/teste.MovieService/DeleteMovie',
            movie__pb2.Command.SerializeToString,
            movie__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
